### PR TITLE
global modifier and summary line

### PR DESCRIPTION
**Pull request by lassic**

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Hey @Iassic — what language do you need the /g modifier for? In general would be happy to add it

**Comment by lassic** [comment]
@ConradIrwin sorry, actually meant to do this PR on my own fork, apologies for the noise.
I needed this for javascript and java I think, there was a capital G in the code, but not lowercase g.

**Comment by ConradIrwin** [comment]
Makes sense!. Btw, I've added you as a committer to this repo — I'd rather
have all work going on in one place. If you want to host it under your
username still that's fine, I'll just send PRs to you.

Conrad

Sent via Superhuman <https://sprh.mn/?vip=conrad.irwin@gmail.com>

**Comment by lassic** [comment]
ok, thanks. let's keep it on your user since you opened it.
not sure if you want my other change though, I just added a summary line separator for easier parsing of the output.

**Comment by ConradIrwin** [comment]
If you want, I think I added something very similar when I was playing with
it.

The output format could definitely be improved, my aim with publishing the
project was to eventually make it into something easy to use, so anything
that helps along that goal is fine.

I don't think we need to worry about backward compatibility for a bit

Conrad

**Pull request closed without merging**
